### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by Moyivv** [Xinyuell/kill_acg#1]
法案“学术包装“没有效果，”政策点“与”开会“的描述内容对不上

**Comment by Xinyuell** [comment]
学术包装：降低工作知识转化消耗5%
几项工作里，只有最后的开会，也就是获取政策点，需要消耗知识。
举例说明，如果现在1级法案，降低5%则知识消耗为95%，所以开会安排一个人，实际效果是，动漫知识-9.5/s，游戏知识-9.5/s，金钱-10/s。
我测试下来是这样的啊？你那里不是吗？还是我描述问题导致你理解不同？

”政策点“与”开会“的描述内容对不上是指？

**Comment by Xinyuell** [comment]
> 法案“学术包装“没有效果，”政策点“与”开会“的描述内容对不上

![image](https://user-images.githubusercontent.com/34654211/139672800-216bb6ba-e536-4426-89e7-653716a19de1.png)

如图（为了方便测试，动漫知识效率和游戏知识效率都是100%，100个人是200/s，被减去95，变成105/s）

PS：这个游戏我就nga水区放了一下，好像被冲水很久了。。话说你怎么玩到的

**Comment by Moyivv** [comment]
点1级学术包装知识消耗减5%，但是得到的政绩点不能少啊，本来消耗10点知识得到1个政绩点，现在消耗9.5点知识得到0.95个政绩点，这不还是10比1吗。
![图片](https://user-images.githubusercontent.com/93498554/139675220-92db3d2f-d5a4-4a94-a9c6-2d86db5df2a6.png)
![图片](https://user-images.githubusercontent.com/93498554/139675399-8dc3e39f-49ef-44ed-b8ba-862bd23e2c38.png)
![图片](https://user-images.githubusercontent.com/93498554/139675431-106f1ed6-f148-4b07-b5d3-890e88209367.png)
政绩点介绍是10比1，开会上写的是10比0.1，实际效果也是10比1。

**Comment by Moyivv** [comment]
我就是载NGA上看到的啊。上面说错了测试的实际效果是10比0.1。

**Comment by Xinyuell** [comment]
> 我就是载NGA上看到的啊。上面说错了测试的实际效果是10比0.1。

懂了！这就改

**Comment by Xinyuell** [comment]
> 我就是载NGA上看到的啊。上面说错了测试的实际效果是10比0.1。

已更新，现在降低消耗不会导致速度也等比降低了
开会的描述可以视为是描述的基准值，实际值是在资源面板描述的（主要是为了减少动态更新）

**Comment by Xinyuell** [comment]
> 我就是载NGA上看到的啊。上面说错了测试的实际效果是10比0.1。

你这个数值 16K的政治背景 应该早就能通关了吧感觉....

**Comment by Moyivv** [comment]
![图片](https://user-images.githubusercontent.com/93498554/139678569-41dd71df-7ccf-4e38-9485-dc62a17e1052.png)
我刷了近一个月了

**Comment by Moyivv** [comment]
两天就能把信徒的两个建筑点满

**Comment by Xinyuell** [comment]
> ![图片](https://user-images.githubusercontent.com/93498554/139678569-41dd71df-7ccf-4e38-9485-dc62a17e1052.png) 我刷了近一个月了

- 举报CD公式：200 / Math.pow(workPeople + 50, 0.4 + prop)
  - workPeople就是你举报的人数，以这个为底数
  - prop是法案，自律公约提升的值，以这个为幂
  
- 举报一次的期望是2 * 0.5+5 * 0.3+50 * 0.2=1250万
   - 举报的三个等级基础值分别是200万、500万、5000万
   - 随机权重是5：3：2
   - 严格审查科技每级提升20%效率

- 基础的ACG文化速度是1百万每秒。低于50%影响力之后每降低10%翻倍，最高16倍
   - 20%以下的时候。每秒1600万这是最大值
   - 这个值，可以被打击acg文化政策降低
   - 所以理论上只要你的举报效率高于每秒1600万*降低效率，就可以通关了
  - 比如降到每秒1250万，然后举报CD控制在每秒1次

**Comment by Moyivv** [comment]
我都是拿满政治背景，再举报的。要不然半个小时重置一次太麻烦了。没有挂机的乐趣

**Comment by Moyivv** [comment]
![图片](https://user-images.githubusercontent.com/93498554/140059795-027b1511-a415-41c2-b63a-799779d1cae0.png)
![图片](https://user-images.githubusercontent.com/93498554/140059871-3010047f-22f2-4f2f-a512-422fdefc42d5.png)
![图片](https://user-images.githubusercontent.com/93498554/140059918-536333f7-5636-498e-81db-0363d4e4772d.png)
我这是卡到bug了？都变NaN了- -！

**Comment by Xinyuell** [comment]
> ![图片](https://user-images.githubusercontent.com/93498554/140059795-027b1511-a415-41c2-b63a-799779d1cae0.png)
> ![图片](https://user-images.githubusercontent.com/93498554/140059871-3010047f-22f2-4f2f-a512-422fdefc42d5.png)
> ![图片](https://user-images.githubusercontent.com/93498554/140059918-536333f7-5636-498e-81db-0363d4e4772d.png)
> 我这是卡到bug了？都变NaN了- -！

额，可以把存档发我一下，我明天可以拿存档查一下

**Comment by Moyivv** [comment]
eyJzb3VyY2VBcnIiOlt7ImNhY2hlVmFsdWUiOjIzOTY1NTQ0NTEwLCJ1bmxvY2siOnRydWUsIklEIjoxfSx7ImNhY2hlVmFsdWUiOjI1ODg1OTEyOTU0NTcuMDM5NiwidW5sb2NrIjp0cnVlLCJJRCI6Mn0seyJjYWNoZVZhbHVlIjozMjU5MDA0NTc0ODguMTk0OCwidW5sb2NrIjp0cnVlLCJJRCI6M30seyJjYWNoZVZhbHVlIjoyMTQ5MTYyOTk0NDEuMTQxNywidW5sb2NrIjp0cnVlLCJJRCI6NH0seyJjYWNoZVZhbHVlIjo1Nzc0ODMwLCJ1bmxvY2siOnRydWUsIklEIjo1fSx7ImNhY2hlVmFsdWUiOjEzMTMxMCwidW5sb2NrIjp0cnVlLCJJRCI6Nn0seyJjYWNoZVZhbHVlIjoyMjA4MTM1NTg5MS40MTEwMjIsInVubG9jayI6dHJ1ZSwiSUQiOjd9LHsiY2FjaGVWYWx1ZSI6NTE3Mjk4LCJ1bmxvY2siOnRydWUsIklEIjo4fV0sImJ1aWxkQXJyeUxpc3QiOlt7ImN1clZhbHVlIjowLCJ1bmxvY2siOnRydWUsIklEIjoxfSx7ImN1clZhbHVlIjowLCJ1bmxvY2siOnRydWUsIklEIjoyfSx7ImN1clZhbHVlIjowLCJ1bmxvY2siOnRydWUsIklEIjozfSx7ImN1clZhbHVlIjo4MTAsInVubG9jayI6dHJ1ZSwiSUQiOjR9LHsiY3VyVmFsdWUiOjI0LCJ1bmxvY2siOnRydWUsIklEIjo1fSx7ImN1clZhbHVlIjoxMzcsInVubG9jayI6dHJ1ZSwiSUQiOjZ9LHsiY3VyVmFsdWUiOjIzMywidW5sb2NrIjp0cnVlLCJJRCI6N30seyJjdXJWYWx1ZSI6MjIsInVubG9jayI6dHJ1ZSwiSUQiOjh9LHsiY3VyVmFsdWUiOjEzNywidW5sb2NrIjp0cnVlLCJJRCI6OX0seyJjdXJWYWx1ZSI6Mjg4MzM2LCJ1bmxvY2siOnRydWUsIklEIjoxMH0seyJjdXJWYWx1ZSI6MjAsInVubG9jayI6dHJ1ZSwiSUQiOjExfSx7ImN1clZhbHVlIjoxMzEsInVubG9jayI6dHJ1ZSwiSUQiOjEyfSx7ImN1clZhbHVlIjoyMTYsInVubG9jayI6dHJ1ZSwiSUQiOjEzfSx7ImN1clZhbHVlIjoxOSwidW5sb2NrIjp0cnVlLCJJRCI6MTR9LHsiY3VyVmFsdWUiOjEyNCwidW5sb2NrIjp0cnVlLCJJRCI6MTV9XSwicG9saWN5QXJyeUxpc3QiOlt7IklEIjowLCJsZXZlbCI6MjE5MX0seyJJRCI6MSwibGV2ZWwiOjB9LHsiSUQiOjIsImxldmVsIjoyODh9LHsiSUQiOjMsImxldmVsIjowfV0sImFjZ1Byb2dyZXNzVmFsdWUiOjE5NzMyNzk5MTAuODAwMDAwMiwiaW5mbHVlbmNlTGV2ZWwiOjcsInJlc2VhcmNoVW5Mb2NrTGlzdCI6WzEsMTAsMTEsMTIsMjIsMiwxMywzMiwxNCwxNSwzLDIzLDMzLDE2LDE3LDQsMTgsMzQsMjQsMTksMjAsNSwyMSwyNSwyNiw2LDcsMjcsOF0sInJlc2VhcmNoQ29tcGxldGUiOlsxLDEwLDExLDEyLDIyLDIsMTMsMzIsMTQsMTUsMywyMywxNiwxNyw0LDMzLDE4LDI0LDE5LDIwLDUsMjEsMzQsMjUsNiwyNiw3LDI3LDhdLCJ3b3JrQ29uZmlnIjpbNTI3ODA4NiwwLDAsMCwxMDAwLDBdLCJhdXRvV29ya0luZGV4IjowLCJuZXdzSUQiOltdLCJ0b3RhbFRpbWUiOjI2ODI5NDc0LCJoaXN0b3J5TG9nSUQiOjUsIlBvbGl0aWNhbERhdGEiOnsidmFsdWUiOjg2NzYwOTgsInJlc3RhcnRUaW1lIjo0NiwidG90YWxUaW1lcyI6MTk2NjQ0NDgzOSwiTGF3TGV2ZWwiOlt7IklEIjowLCJsZXZlbCI6OX0seyJJRCI6MSwibGV2ZWwiOjExfSx7IklEIjoyLCJsZXZlbCI6ODJ9LHsiSUQiOjMsImxldmVsIjo0MDB9LHsiSUQiOjQsImxldmVsIjo3Nn1dfSwic2V0dGluZyI6eyJjbG9zZUd1aWRlIjp0cnVlLCJjbG9zZUxvZyI6dHJ1ZSwiY2xvc2VOZXciOmZhbHNlLCJjbG9zZUNvbXBsYWluIjp0cnVlLCJoYXNTaG93QWNnR3VpZGUiOnRydWUsImJ1aWxkQWN0aXZlTmFtZSI6WyIzIiwiNCIsIjIiXSwidGltZU5vdyI6MTYzNjA3MTEyMzI0MywiZG91YmxlVGltZSI6NDMxNzk4NjV9fQ==

**Comment by Xinyuell** [comment]
> eyJzb3VyY2VBcnIiOlt7ImNhY2hlVmFsdWUiOjIzOTY1NTQ0NTEwLCJ1bmxvY2siOnRydWUsIklEIjoxfSx7ImNhY2hlVmFsdWUiOjI1ODg1OTEyOTU0NTcuMDM5NiwidW5sb2NrIjp0cnVlLCJJRCI6Mn0seyJjYWNoZVZhbHVlIjozMjU5MDA0NTc0ODguMTk0OCwidW5sb2NrIjp0cnVlLCJJRCI6M30seyJjYWNoZVZhbHVlIjoyMTQ5MTYyOTk0NDEuMTQxNywidW5sb2NrIjp0cnVlLCJJRCI6NH0seyJjYWNoZVZhbHVlIjo1Nzc0ODMwLCJ1bmxvY2siOnRydWUsIklEIjo1fSx7ImNhY2hlVmFsdWUiOjEzMTMxMCwidW5sb2NrIjp0cnVlLCJJRCI6Nn0seyJjYWNoZVZhbHVlIjoyMjA4MTM1NTg5MS40MTEwMjIsInVubG9jayI6dHJ1ZSwiSUQiOjd9LHsiY2FjaGVWYWx1ZSI6NTE3Mjk4LCJ1bmxvY2siOnRydWUsIklEIjo4fV0sImJ1aWxkQXJyeUxpc3QiOlt7ImN1clZhbHVlIjowLCJ1bmxvY2siOnRydWUsIklEIjoxfSx7ImN1clZhbHVlIjowLCJ1bmxvY2siOnRydWUsIklEIjoyfSx7ImN1clZhbHVlIjowLCJ1bmxvY2siOnRydWUsIklEIjozfSx7ImN1clZhbHVlIjo4MTAsInVubG9jayI6dHJ1ZSwiSUQiOjR9LHsiY3VyVmFsdWUiOjI0LCJ1bmxvY2siOnRydWUsIklEIjo1fSx7ImN1clZhbHVlIjoxMzcsInVubG9jayI6dHJ1ZSwiSUQiOjZ9LHsiY3VyVmFsdWUiOjIzMywidW5sb2NrIjp0cnVlLCJJRCI6N30seyJjdXJWYWx1ZSI6MjIsInVubG9jayI6dHJ1ZSwiSUQiOjh9LHsiY3VyVmFsdWUiOjEzNywidW5sb2NrIjp0cnVlLCJJRCI6OX0seyJjdXJWYWx1ZSI6Mjg4MzM2LCJ1bmxvY2siOnRydWUsIklEIjoxMH0seyJjdXJWYWx1ZSI6MjAsInVubG9jayI6dHJ1ZSwiSUQiOjExfSx7ImN1clZhbHVlIjoxMzEsInVubG9jayI6dHJ1ZSwiSUQiOjEyfSx7ImN1clZhbHVlIjoyMTYsInVubG9jayI6dHJ1ZSwiSUQiOjEzfSx7ImN1clZhbHVlIjoxOSwidW5sb2NrIjp0cnVlLCJJRCI6MTR9LHsiY3VyVmFsdWUiOjEyNCwidW5sb2NrIjp0cnVlLCJJRCI6MTV9XSwicG9saWN5QXJyeUxpc3QiOlt7IklEIjowLCJsZXZlbCI6MjE5MX0seyJJRCI6MSwibGV2ZWwiOjB9LHsiSUQiOjIsImxldmVsIjoyODh9LHsiSUQiOjMsImxldmVsIjowfV0sImFjZ1Byb2dyZXNzVmFsdWUiOjE5NzMyNzk5MTAuODAwMDAwMiwiaW5mbHVlbmNlTGV2ZWwiOjcsInJlc2VhcmNoVW5Mb2NrTGlzdCI6WzEsMTAsMTEsMTIsMjIsMiwxMywzMiwxNCwxNSwzLDIzLDMzLDE2LDE3LDQsMTgsMzQsMjQsMTksMjAsNSwyMSwyNSwyNiw2LDcsMjcsOF0sInJlc2VhcmNoQ29tcGxldGUiOlsxLDEwLDExLDEyLDIyLDIsMTMsMzIsMTQsMTUsMywyMywxNiwxNyw0LDMzLDE4LDI0LDE5LDIwLDUsMjEsMzQsMjUsNiwyNiw3LDI3LDhdLCJ3b3JrQ29uZmlnIjpbNTI3ODA4NiwwLDAsMCwxMDAwLDBdLCJhdXRvV29ya0luZGV4IjowLCJuZXdzSUQiOltdLCJ0b3RhbFRpbWUiOjI2ODI5NDc0LCJoaXN0b3J5TG9nSUQiOjUsIlBvbGl0aWNhbERhdGEiOnsidmFsdWUiOjg2NzYwOTgsInJlc3RhcnRUaW1lIjo0NiwidG90YWxUaW1lcyI6MTk2NjQ0NDgzOSwiTGF3TGV2ZWwiOlt7IklEIjowLCJsZXZlbCI6OX0seyJJRCI6MSwibGV2ZWwiOjExfSx7IklEIjoyLCJsZXZlbCI6ODJ9LHsiSUQiOjMsImxldmVsIjo0MDB9LHsiSUQiOjQsImxldmVsIjo3Nn1dfSwic2V0dGluZyI6eyJjbG9zZUd1aWRlIjp0cnVlLCJjbG9zZUxvZyI6dHJ1ZSwiY2xvc2VOZXciOmZhbHNlLCJjbG9zZUNvbXBsYWluIjp0cnVlLCJoYXNTaG93QWNnR3VpZGUiOnRydWUsImJ1aWxkQWN0aXZlTmFtZSI6WyIzIiwiNCIsIjIiXSwidGltZU5vdyI6MTYzNjA3MTEyMzI0MywiZG91YmxlVGltZSI6NDMxNzk4NjV9fQ==

- 看来一下存档，应该是你政策点的足够高
- 扶持教育那一项每级降低30%，比如50级是0.7的50次方，消耗就是原来的10e-8，js里面的小数太小就被认为是0了
- 所以金钱消耗变零了，其他没点科技的建筑就是正常的
